# Generated by Django 2.2.16 on 2020-09-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bngvnbvnb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jkjhkhjhk", models.BigIntegerField()),
                ("ngghgjhgjhg", models.GenericIPAddressField(protocol="IPv4")),
                (
                    "nbmbnmnbmnb",
                    models.DecimalField(decimal_places=100, max_digits=300),
                ),
            ],
        ),
    ]
