# Generated by Django 2.2.16 on 2020-09-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nbvnb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bngvnbvnb",
            name="nbmbnmnbmnb",
        ),
        migrations.RemoveField(
            model_name="bngvnbvnb",
            name="ngghgjhgjhg",
        ),
    ]
