# Generated by Django 2.2.16 on 2020-09-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200918_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hgjgjhg',
        ),
    ]
