# Generated by Django 2.2.16 on 2020-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_hgjgjhg"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hgttututyut",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hjgggjg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
