# Generated by Django 2.2.16 on 2020-09-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200918_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hgttututyut',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hjgggjg',
        ),
    ]
