# Generated by Django 2.2.16 on 2020-09-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20200918_0642"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gfghfg",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hjgjhgjg",
        ),
    ]
