# Generated by Django 2.2.16 on 2020-09-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_vnbvnv'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nbvbnvnbv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
